server:
  port: 11012
  
spring:
  datasource:
    url: jdbc:mysql://193.168.1.199:3307/wsic_elec?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: wellsun_2019
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
  session:
    store-type: redis
    timeout: 1800
    redis:
      namespace: wsic-elec
  application:
    name: wsic-elec-business
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations:
  - classpath:mapper/*Mapper.xml
  type-aliases-package: com.ws.wsic.elec.business.model
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11010/eureka/  # 服务中心地址
      
feign:
  httpclient:
    connection-timeout: 30000

     